PREFIX = /etc/mevent

all: noexist

noexist:

install:
#	install -d $(PREFIX)
#	install -m 0644 server.hdf $(PREFIX)/
#	install -m 0644 client.hdf $(PREFIX)/

uninstall:
	rm -f $(PREFIX)/server.hdf
	rm -f $(PREFIX)/client.hdf

clean:
